color0 #49454e
color1 #ffb4ab
color2 #cfbdfe
color3 #cbc2db
color4 #efb8c8
color5 #cfbdfe
color6 #cbc2db
color7 #e6e0e9
color8 #948f99
color9 #ffb4ab
color10 #cfbdfe
color11 #cbc2db
color12 #efb8c8
color13 #cfbdfe
color14 #cbc2db
color15 #e6e0e9

cursor                #e6e0e9
cursor_text_color     #141218
background            #141218
foreground            #e6e0e9
selection_foreground  #cac4cf
selection_background  #49454e
active_border_color   #cfbdfe
inactive_border_color #49454e
url_color             #cfbdfe

active_tab_foreground   #36275d
active_tab_background   #cfbdfe
inactive_tab_foreground #cac4cf
inactive_tab_background #49454e
cursor_trail_color      #cac4cf
