color0 #3f484a
color1 #ffb4ab
color2 #81d3dd
color3 #b1cbcf
color4 #b8c6ea
color5 #81d3dd
color6 #b1cbcf
color7 #dee4e4
color8 #899294
color9 #ffb4ab
color10 #81d3dd
color11 #b1cbcf
color12 #b8c6ea
color13 #81d3dd
color14 #b1cbcf
color15 #dee4e4

cursor                #dee4e4
cursor_text_color     #0e1415
background            #0e1415
foreground            #dee4e4
selection_foreground  #bec8c9
selection_background  #3f484a
active_border_color   #81d3dd
inactive_border_color #3f484a
url_color             #81d3dd

active_tab_foreground   #00363b
active_tab_background   #81d3dd
inactive_tab_foreground #bec8c9
inactive_tab_background #3f484a
cursor_trail_color      #bec8c9
