color0 #52443d
color1 #ffb4ab
color2 #ffb691
color3 #e6beab
color4 #cfc890
color5 #ffb691
color6 #e6beab
color7 #f0dfd8
color8 #a08d85
color9 #ffb4ab
color10 #ffb691
color11 #e6beab
color12 #cfc890
color13 #ffb691
color14 #e6beab
color15 #f0dfd8

cursor                #f0dfd8
cursor_text_color     #1a120e
background            #1a120e
foreground            #f0dfd8
selection_foreground  #d7c2b9
selection_background  #52443d
active_border_color   #ffb691
inactive_border_color #52443d
url_color             #ffb691

active_tab_foreground   #542202
active_tab_background   #ffb691
inactive_tab_foreground #d7c2b9
inactive_tab_background #52443d
cursor_trail_color      #d7c2b9
