-- Generated by nwg-displays on 2026-09-03 at 18:41:48. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1920x1080@60.0",
    position = "1800x0",
    scale = 1.0,
    vrr = 0
})
hl.monitor({
    output = "HEADLESS-1",
    mode = "1800x1200@60.0",
    position = "0x590",
    scale = 1,
    vrr = 0
})
